-- UDM Registry: Industry Crosswalk seeded from Universal Decoding Matrix_Master.xlsx
-- (Industry Crosswalk sheet — ISIC Rev.4 ontology anchor with NAICS 2022 + GICS bridges).
CREATE TABLE IF NOT EXISTS udm_crosswalk (
  ontology_id TEXT PRIMARY KEY,
  industry TEXT,
  isic_section TEXT,
  isic_division TEXT,
  isic_title TEXT,
  naics_bridge TEXT,
  gics_sector TEXT,
  gics_industry TEXT,
  mapping_status TEXT,
  bridge_path TEXT
);
DELETE FROM udm_crosswalk;
INSERT INTO udm_crosswalk VALUES ('GI-001','Crop, animal, and mixed farming','A','1','Crop and animal production, hunting and related service activities','11: 111,112,115','Consumer Staples; Materials','Food Products; Agricultural Products & Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-002','Forestry and logging','A','2','Forestry and logging','11: 113','Materials','Paper & Forest Products','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-003','Fishing and aquaculture','A','3','Fishing and aquaculture','11: 114','Consumer Staples','Food Products','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-004','Coal and lignite mining','B','5','Mining of coal and lignite','21: 212','Energy','Coal & Consumable Fuels','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-005','Oil and gas extraction','B','6','Extraction of crude petroleum and natural gas','21: 211','Energy','Oil & Gas Exploration & Production','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-006','Metal ore mining','B','7','Mining of metal ores','21: 212','Materials','Metals & Mining','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-007','Nonmetallic mineral mining and quarrying','B','8','Other mining and quarrying','21: 212','Materials','Construction Materials; Metals & Mining','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-008','Mining support services','B','9','Mining support service activities','21: 213','Energy; Materials','Oil & Gas Equipment & Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-009','Food manufacturing','C','10','Manufacture of food products','31-33: 311','Consumer Staples','Food Products','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-010','Beverage manufacturing','C','11','Manufacture of beverages','31-33: 312','Consumer Staples','Beverages','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-011','Tobacco manufacturing','C','12','Manufacture of tobacco products','31-33: 312','Consumer Staples','Tobacco','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-012','Textile manufacturing','C','13','Manufacture of textiles','31-33: 313','Consumer Discretionary','Textiles, Apparel & Luxury Goods','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-013','Apparel manufacturing','C','14','Manufacture of wearing apparel','31-33: 315','Consumer Discretionary','Textiles, Apparel & Luxury Goods','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-014','Leather and related goods manufacturing','C','15','Manufacture of leather and related products','31-33: 316','Consumer Discretionary','Textiles, Apparel & Luxury Goods','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-015','Wood product manufacturing','C','16','Manufacture of wood and products of wood and cork, except furniture','31-33: 321','Materials; Industrials','Paper & Forest Products; Building Products','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-016','Paper manufacturing','C','17','Manufacture of paper and paper products','31-33: 322','Materials','Paper & Forest Products; Paper Packaging','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-017','Printing and recorded media reproduction','C','18','Printing and reproduction of recorded media','31-33: 323','Industrials; Communication Services','Commercial Printing; Media','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-018','Petroleum and coal product manufacturing','C','19','Manufacture of coke and refined petroleum products','31-33: 324','Energy','Oil & Gas Refining & Marketing','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-019','Chemical manufacturing','C','20','Manufacture of chemicals and chemical products','31-33: 325','Materials','Chemicals','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-020','Pharmaceutical manufacturing','C','21','Manufacture of basic pharmaceutical products and pharmaceutical preparations','31-33: 325','Health Care','Pharmaceuticals; Biotechnology','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-021','Rubber and plastics manufacturing','C','22','Manufacture of rubber and plastics products','31-33: 326','Materials; Consumer Discretionary','Commodity Chemicals; Auto Components','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-022','Nonmetallic mineral product manufacturing','C','23','Manufacture of other non-metallic mineral products','31-33: 327','Materials','Construction Materials','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-023','Primary metal manufacturing','C','24','Manufacture of basic metals','31-33: 331','Materials','Metals & Mining; Steel','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-024','Fabricated metal product manufacturing','C','25','Manufacture of fabricated metal products, except machinery and equipment','31-33: 332','Industrials','Machinery; Building Products','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-025','Computer, electronic, and optical product manufacturing','C','26','Manufacture of computer, electronic and optical products','31-33: 334','Information Technology','Technology Hardware; Semiconductors','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-026','Electrical equipment manufacturing','C','27','Manufacture of electrical equipment','31-33: 335','Industrials; Information Technology','Electrical Equipment; Electronic Components','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-027','Machinery and equipment manufacturing','C','28','Manufacture of machinery and equipment n.e.c.','31-33: 333','Industrials','Machinery','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-028','Motor vehicle manufacturing','C','29','Manufacture of motor vehicles, trailers and semi-trailers','31-33: 336','Consumer Discretionary','Automobiles; Auto Components','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-029','Other transport equipment manufacturing','C','30','Manufacture of other transport equipment','31-33: 336','Industrials; Consumer Discretionary','Aerospace & Defense; Leisure Products','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-030','Furniture manufacturing','C','31','Manufacture of furniture','31-33: 337','Consumer Discretionary','Household Durables','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-031','Miscellaneous manufacturing','C','32','Other manufacturing','31-33: 339','Health Care; Consumer Discretionary; Industrials','Health Care Equipment; Leisure Products','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-032','Repair and installation of machinery','C','33','Repair and installation of machinery and equipment','31-33; 81: 811','Industrials','Commercial Services & Supplies','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-033','Electricity, gas, steam, and air conditioning supply','D','35','Electricity, gas, steam and air conditioning supply','22: 221','Utilities','Electric Utilities; Gas Utilities; Multi-Utilities','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-034','Water supply','E','36','Water collection, treatment and supply','22: 221','Utilities','Water Utilities','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-035','Sewerage','E','37','Sewerage','22: 221; 56: 562','Utilities; Industrials','Water Utilities; Environmental Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-036','Waste management and materials recovery','E','38','Waste collection, treatment and disposal activities; materials recovery','56: 562','Industrials','Environmental & Facilities Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-037','Remediation and environmental cleanup','E','39','Remediation activities and other waste management services','56: 562','Industrials','Environmental & Facilities Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-038','Building construction','F','41','Construction of buildings','23: 236','Industrials; Consumer Discretionary','Construction & Engineering; Homebuilding','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-039','Civil engineering construction','F','42','Civil engineering','23: 237','Industrials','Construction & Engineering','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-040','Specialty trade contracting','F','43','Specialized construction activities','23: 238','Industrials','Construction & Engineering; Building Products','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-041','Motor vehicle wholesale, retail, and repair','G','45','Wholesale and retail trade and repair of motor vehicles and motorcycles','44-45: 441; 42: 423; 81: 811','Consumer Discretionary','Automobile Retail; Auto Parts','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-042','Wholesale trade','G','46','Wholesale trade, except of motor vehicles and motorcycles','42: 423,424,425','Industrials; Consumer Staples; Health Care','Trading Companies & Distributors','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-043','Retail trade','G','47','Retail trade, except of motor vehicles and motorcycles','44-45: 444-459','Consumer Discretionary; Consumer Staples','Retailing; Food & Staples Retailing','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-044','Land transport and pipelines','H','49','Land transport and transport via pipelines','48-49: 482,484,485,486','Industrials; Energy','Ground Transportation; Oil & Gas Storage & Transportation','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-045','Water transport','H','50','Water transport','48-49: 483','Industrials','Marine Transportation','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-046','Air transport','H','51','Air transport','48-49: 481','Industrials','Passenger Airlines; Air Freight & Logistics','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-047','Warehousing and transport support','H','52','Warehousing and support activities for transportation','48-49: 488,493','Industrials','Transportation Infrastructure; Logistics','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-048','Postal and courier services','H','53','Postal and courier activities','48-49: 491,492','Industrials','Air Freight & Logistics','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-049','Accommodation','I','55','Accommodation','72: 721','Consumer Discretionary','Hotels, Restaurants & Leisure','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-050','Food and beverage services','I','56','Food and beverage service activities','72: 722','Consumer Discretionary','Restaurants','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-051','Publishing','J','58','Publishing activities','51: 513','Communication Services; Information Technology','Media; Software','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-052','Film, video, television, sound, and music production','J','59','Motion picture, video and television programme production, sound recording and music publishing activities','51: 512','Communication Services','Entertainment; Movies & Entertainment','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-053','Broadcasting and programming','J','60','Programming and broadcasting activities','51: 516','Communication Services','Media','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-054','Telecommunications','J','61','Telecommunications','51: 517','Communication Services','Telecommunication Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-055','Software and IT services','J','62','Computer programming, consultancy and related activities','51: 518; 54: 541','Information Technology','Software; IT Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-056','Data, web, libraries, archives, and information services','J','63','Information service activities','51: 518,519','Communication Services; Information Technology','Interactive Media; Internet Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-057','Banking and financial intermediation','K','64','Financial service activities, except insurance and pension funding','52: 521,522,523,525','Financials','Banks; Capital Markets; Consumer Finance','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-058','Insurance and pensions','K','65','Insurance, reinsurance and pension funding, except compulsory social security','52: 524,525','Financials','Insurance','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-059','Financial and insurance support services','K','66','Activities auxiliary to financial service and insurance activities','52: 523,524,525','Financials','Capital Markets; Exchanges & Data; Brokers','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-060','Real estate','L','68','Real estate activities','53: 531','Real Estate','Real Estate Management & Development; Equity REITs','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-061','Legal and accounting services','M','69','Legal and accounting activities','54: 541','Industrials','Research & Consulting Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-062','Head offices and management consulting','M','70','Activities of head offices; management consultancy activities','55: 551; 54: 541','Industrials','Research & Consulting Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-063','Architecture, engineering, and testing','M','71','Architectural and engineering activities; technical testing and analysis','54: 541','Industrials','Construction & Engineering; Consulting','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-064','Scientific research and development','M','72','Scientific research and development','54: 541','Health Care; IT; Industrials','Life Sciences Tools; Consulting','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-065','Advertising and market research','M','73','Advertising and market research','54: 541','Communication Services; Industrials','Advertising; Research & Consulting','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-066','Other professional and technical services','M','74','Other professional, scientific and technical activities','54: 541','Industrials; Consumer Discretionary','Research & Consulting; Commercial Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-067','Veterinary services','M','75','Veterinary activities','54: 541','Health Care; Consumer Staples','Health Care Providers; Pet Care bridge','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-068','Rental and leasing','N','77','Rental and leasing activities','53: 532,533','Industrials; Consumer Discretionary','Trading Companies; Specialized Consumer Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-069','Employment services','N','78','Employment activities','56: 561','Industrials','Human Resource & Employment Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-070','Travel agencies and tour operators','N','79','Travel agency, tour operator, reservation service and related activities','56: 561','Consumer Discretionary','Hotels, Restaurants & Leisure','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-071','Security and investigation','N','80','Security and investigation activities','56: 561','Industrials','Security & Alarm Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-072','Facilities support and landscaping','N','81','Services to buildings and landscape activities','56: 561','Industrials','Environmental & Facilities Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-073','Office administration and business support','N','82','Office administrative, office support and other business support activities','56: 561','Industrials','Commercial Services & Supplies','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-074','Public administration and defense','O','84','Public administration and defence; compulsory social security','92: 921-928','N/A / Government','Mostly outside GICS company taxonomy','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-075','Education','P','85','Education','61: 611','Consumer Discretionary','Education Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-076','Human health services','Q','86','Human health activities','62: 621,622','Health Care','Health Care Providers & Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-077','Residential care','Q','87','Residential care activities','62: 623','Health Care','Health Care Facilities; Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-078','Social assistance','Q','88','Social work activities without accommodation','62: 624','Health Care; Consumer Discretionary','Health Care Services; Specialized Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-079','Creative arts and entertainment','R','90','Creative, arts and entertainment activities','71: 711','Communication Services; Consumer Discretionary','Entertainment; Leisure Facilities','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-080','Museums, libraries, archives, and cultural institutions','R','91','Libraries, archives, museums and other cultural activities','71: 712; 51: 519','Communication Services; Consumer Discretionary','Media; Leisure Facilities bridge','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-081','Gambling and betting','R','92','Gambling and betting activities','71: 713','Consumer Discretionary','Casinos & Gaming','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-082','Sports, amusement, and recreation','R','93','Sports activities and amusement and recreation activities','71: 711,713','Consumer Discretionary; Communication Services','Leisure Facilities; Entertainment','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-083','Membership organizations','S','94','Activities of membership organizations','81: 813','N/A / Nonprofit','Mostly outside GICS company taxonomy','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-084','Repair of computers and personal goods','S','95','Repair of computers and personal and household goods','81: 811','Information Technology; Consumer Discretionary','Technology Hardware support; Consumer Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-085','Other personal services','S','96','Other personal service activities','81: 812','Consumer Discretionary','Specialized Consumer Services','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-086','Household employers','T','97','Activities of households as employers of domestic personnel','81: 814','N/A / Household sector','Outside GICS company taxonomy','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-087','Household production for own use','T','98','Undifferentiated goods- and services-producing activities of private households for own use','Household sector bridge','N/A / Household sector','Outside GICS company taxonomy','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');
INSERT INTO udm_crosswalk VALUES ('GI-088','Extraterritorial organizations','U','99','Activities of extraterritorial organizations and bodies','92: 928 bridge','N/A / Supranational','Outside GICS company taxonomy','Ontology bridge; verify with official concordance for regulatory/statistical use','ISIC Division → NAICS sector/subsector → GICS sector/industry bridge');