<?xml version="1.0"?>
<definitions name="WellFilingService" targetNamespace="urn:wellview:filing"
  xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:wellview:filing">
  <types><xsd:schema targetNamespace="urn:wellview:filing">
    <xsd:element name="SubmitFiling"><xsd:complexType><xsd:sequence>
      <xsd:element name="api14" type="xsd:string"/>
      <xsd:element name="form" type="xsd:string"/>
      <xsd:element name="period" type="xsd:string" minOccurs="0"/>
    </xsd:sequence></xsd:complexType></xsd:element>
    <xsd:element name="GetFilingStatus"><xsd:complexType><xsd:sequence>
      <xsd:element name="filingId" type="xsd:string"/>
    </xsd:sequence></xsd:complexType></xsd:element>
  </xsd:schema></types>
  <message name="SubmitFilingIn"><part name="parameters" element="tns:SubmitFiling"/></message>
  <message name="GetFilingStatusIn"><part name="parameters" element="tns:GetFilingStatus"/></message>
  <portType name="FilingPort">
    <operation name="SubmitFiling"><documentation>Submit a regulatory filing draft (held for human submission).</documentation><input message="tns:SubmitFilingIn"/></operation>
    <operation name="GetFilingStatus"><documentation>Look up the status of a filing.</documentation><input message="tns:GetFilingStatusIn"/></operation>
  </portType>
  <binding name="FilingBinding" type="tns:FilingPort">
    <operation name="SubmitFiling"><soap:operation soapAction="urn:wellview:filing/SubmitFiling"/></operation>
    <operation name="GetFilingStatus"><soap:operation soapAction="urn:wellview:filing/GetFilingStatus"/></operation>
  </binding>
  <service name="WellFilingService"><port name="p" binding="tns:FilingBinding">
    <soap:address location="https://soap.example.com/filing"/></port></service>
</definitions>